apiVersion: v1
kind: Secret
metadata:
  name: webfolder-secret
  namespace: kloud-apps
type: Opaque
stringData:
  DATABASE_URL: "postgresql://postgres:YOUR_PASSWORD@postgres.kloud-db.svc.cluster.local:5432/webfolder"
  JWT_SECRET: "CHANGE_THIS"
  JWT_EXPIRES_IN: "30d"
  S3_ENDPOINT: "http://minio.kloud-apps.svc.cluster.local:9000"
  S3_REGION: "us-east-1"
  S3_ACCESS_KEY: "CHANGE_THIS"
  S3_SECRET_KEY: "CHANGE_THIS"
  S3_BUCKET: "webfolder"
